teleop_twist_joy_node:
  ros__parameters:
    axis_linear:
      x: 2

    scale_linear:
      x: -3.0
    
    axis_angular:
      yaw: 1

    scale_angular:
      yaw: 5.0

    enable_button: 0
    enable_turbo_button: 1

