teleop_twist_joy_node:
  ros__parameters:
    axis_linear:
      x: 1

    scale_linear:
      x: -1.0

    axis_angular:
      yaw: 0

    scale_angular:
      yaw: 2.0

    enable_button: 0
    enable_turbo_button: 1

