ekf_filter_node_odom:
  ros__parameters:
    frequency: 30.0
    sensor_timeout: 0.1
    two_d_mode: true
    transform_time_offset: 0.0
    transform_timeout: 0.0
    print_diagnostics: true
    debug: false

    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

    odom0: diff_cont/odom
    odom0_config: [false, false, false,
                  false, false, false,
                  true, true, false,
                  false, false, true,
                  false, false, false]
    odom0_queue_size: 10
    odom0_differential: false
    odom0_relative: false

#    odom1: zed2/zed_node/odom
#    odom1_config: [true, true, true,
#                  false, false, true,
#                  false, false, false,
#                  false, false, false,
#                  false, false, false]
#    odom1_queue_size: 10
#    odom1_differential: true
#    odom1_relative: false
#
    imu0: zed2i/zed_node/imu/data
    imu0_config: [false, false, false,
                  false,  false,  false,
                  false, false, false,
                  false,  false,  true,
                  true,  true,  false]
    imu0_differential: false
    imu0_relative: false
    imu0_queue_size: 10
    imu0_remove_gravitational_acceleration: true
#
#    use_control: false
#
    process_noise_covariance: [1e-3, 1e-3, 1e-3, 0.3, 0.3, 0.01, 0.5, 0.5, 0.1, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3]
#
    initial_estimate_covariance: [1e-9, 1e-9, 1e-9, 1.0, 1.0, 1e-9, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
#

ekf_filter_node_map:
  ros__parameters:
    frequency: 30.0
    sensor_timeout: 0.1
    two_d_mode: true
    transform_time_offset: 0.0
    transform_timeout: 0.0
    print_diagnostics: true
    debug: false

    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: map

    odom0: diff_cont/odom
    odom0_config: [false, false, false,
                  false, false, false,
                  true, true, true,
                  false, false, false,
                  false, false, false]
    odom0_queue_size: 10
    odom0_differential: false
    odom0_relative: false

#    odom1: zed2/zed_node/odom
#    odom1_config: [true, true, true,
#                  false, false, true,
#                  false, false, false,
#                  false, false, false,
#                  false, false, false]
#    odom1_queue_size: 10
#    odom1_differential: true
#    odom1_relative: false

    imu0: zed2i/zed_node/imu/data
    imu0_config: [false, false, false,
                  false,  false,  false,
                  false, false, false,
                  true,  true,  true,
                  true,  true,  true]
    imu0_differential: false
    imu0_relative: false
    imu0_queue_size: 10
    imu0_remove_gravitational_acceleration: true

#    imu1: gps/navheading
#    imu1_config: [false, false, false,
#                  false,  false,  true,
#                  false, false, false,
#                  false,  false,  false,
#                  false,  false,  false]
#    imu1_differential: false
#    imu1_relative: false
#    imu1_queue_size: 10
#    imu1_remove_gravitational_acceleration: false

    pose0: pose
    pose0_config: [false,  false,  false,
                  false, false, true,
                  false, false, false,
                  false, false, false,
                  false, false, false]

    odom1: odometry/gps
    odom1_config: [true,  true,  false,
                  false, false, false,
                  false, false, false,
                  false, false, false,
                  false, false, false]
    odom1_queue_size: 10
    odom1_differential: false
    odom1_relative: false

    use_control: false

    process_noise_covariance: [50.0, 50.0, 1e-3, 0.3, 0.3, 1.0, 0.5, 0.5, 0.1, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3]

    initial_estimate_covariance: [1.0, 1.0, 1e-9, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]

navsat_transform:
  ros__parameters:
    frequency: 30.0
    delay: 3.0
    magnetic_declination_radians: -0.116
    yaw_offset: 0.0
    zero_altitude: false
    #datum: '[40.469386, -86.990096, 0, map, base_link]'
    publish_filtered_gps: true
    use_odometry_yaw: false
    wait_for_datum: false
